// Code generated by "stringer -type=AssertTargetType -linecomment"; DO NOT EDIT.

package assert

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReceiverFunction-0]
	_ = x[Function-1]
	_ = x[Struct-2]
	_ = x[Variable-3]
	_ = x[Parameter-4]
	_ = x[Condition-5]
	_ = x[Other-6]
}

const _AssertTargetType_name = "receiver functionfunctionstructvariableparameterconditionelement"

var _AssertTargetType_index = [...]uint8{0, 17, 25, 31, 39, 48, 57, 64}

func (i AssertTargetType) String() string {
	if i < 0 || i >= AssertTargetType(len(_AssertTargetType_index)-1) {
		return "AssertTargetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AssertTargetType_name[_AssertTargetType_index[i]:_AssertTargetType_index[i+1]]
}
